sitetest/carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.CartAddView.as_view(), name='cart_add'),
    # path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.CartChangeView.as_view(), name='cart_change'),
    path('cart_remove/', views.CartRemoveView.as_view(), name='cart_remove'),
]

sitetest/sitetest/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from pract.views import page_not_found

from sitetest import settings

from django.conf.urls import handler404


urlpatterns = [
    path('', include('pract.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('carts/', include('carts.urls', namespace='carts')),   
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found
admin.site.site_header = "Карамелька админ"
admin.site.index_title = "Продукция"

sitetest/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
     path('login/', views.LoginUserView.as_view(), name='login'),     #uers:login
     path('logout/', LogoutView.as_view(), name='logout'),   #uers:logout
     path('register/', views.RegisterUserView.as_view(), name='register'),
     path('profile/', views.ProfileUser.as_view(), name='profile'),
     path('password-change/', views.UserPasswordChange.as_view(), name='password-change'),
     # path('users-cart/', views.UserCartView.as_view(), name='users_cart'),  



     path('password-change/done/',
          PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
          name='password_change_done'),

     path('password-reset/',
          PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                        email_template_name='users/password_reset_email.html',
                                        success_url=reverse_lazy("users:password_reset_done")),
          name='password_reset'),

     path('password-reset/done/',
          PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
          name='password_reset_done'),

     path('password-reset/<uidb64>/<token>',
          PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                             success_url=reverse_lazy("users:password_reset_complete")),
          name='password_reset_confirm'),

     path('password-reset/complete/',
          PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
          name='password_reset_complete'),

]

sitetest/orders/models.py
from django.db import models
from pract.models import Goods

from users.models import User
from django.conf import settings

class OrderitemQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    requires_delivery = models.BooleanField(default=False, verbose_name="Требуется доставка")
    delivery_adress = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    payment_on_get = models.BooleanField(default=False, verbose_name="Оплата при получении")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")


    postal_code = models.CharField(max_length=20, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    updated_timestamp = models.DateTimeField(auto_now=True, verbose_name="Дата обновления заказа")
    stripe_id = models.CharField(max_length=250, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)


    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ("id",)

    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"
    
    def get_stripe_url(self):
        if not self.stripe_id:
            return ''
        if '_test_' in settings.STRIPE_SECRET_KEY:
            path = '/test/'
        else:
            path = '/'
        return f'https://dashboard.stripe.com{path}payments/{self.stripe_id}'

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Goods, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"
        ordering = ("id",)

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

sitetest/pract/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

# def translit_to_eng(s: str) -> str:
#     d = {'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd',
#          'е': 'e', 'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i', 'к': 'k',
#          'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r',
#          'с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х': 'h', 'ц': 'c', 'ч': 'ch',
#          'ш': 'sh', 'щ': 'shch', 'ь': '', 'ы': 'y', 'ъ': '', 'э': 'r', 'ю': 'yu', 'я': 'ya'}
#
#     return "".join(map(lambda x: d[x] if d.get(x, False) else x, s.lower()))




class StockManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(quantity__gt=0)
    
class Goods(models.Model):


    title = models.CharField(max_length=255, verbose_name='Название')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='Ссылка',
                            validators=[
                            MinLengthValidator(5, message='Минимум 5 символов'),
                            MaxLengthValidator(100, message='Максимум 100 символов'),
                           ])
    

    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2, verbose_name='Скидка в %')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')


    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', default=None, blank=True,
                              null=True, verbose_name='Фото')
    content = models.TextField(blank=True, verbose_name='Описание')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создание')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Врем обновления')

    cat = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='products_by_cat', verbose_name='Категория')
    sup = models.ForeignKey('Supplier', on_delete=models.PROTECT, related_name='products_by_sup', verbose_name='Поставщик')

    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL,
                               related_name='products_changes', null=True, default=None, verbose_name='Редактировал')
    

    objects = models.Manager()
    stocked = StockManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Вся продукция'
        verbose_name_plural = 'Вся продукция'
        ordering = ['time_create']
        indexes = [
            models.Index(fields=['time_create'])
        ]

    def get_absolute_url(self):
        return reverse('tovar', kwargs={'tovar_slug': self.slug} )


    def display_id(self):
        return f"{self.id:05}"
    


    def sell_price(self):
        if self.discount:
            return round(self.price - self.price*self.discount/100, 2)
        
        return self.price






class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='Ссылка')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'продукция по категориям'
        verbose_name_plural = 'продукция по категориям'



class Supplier(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Поставщик')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='Ссылка')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'продукция по поставщикам'
        verbose_name_plural = 'продукция по поставщикам'



class UploadFiles(models.Model):
    file = models.FileField(upload_to='uploads_model')

sitetest/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    photo = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True, null=True, verbose_name='Фото')
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения')
    phone_number = models.CharField(max_length=20, blank=True, null=True)

sitetest/users/forms.py
import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, SetPasswordMixin
from django.urls import reverse_lazy


class LoginUserForm(AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()

    # username = forms.CharField(label='Логин или E-mail',
    #                            widget=forms.TextInput(attrs={'class': 'form-input'}))

    # password = forms.CharField(label='Пароль',
    #                            widget=forms.PasswordInput(attrs={'class': 'form-input'}))




# class RegisterUserForm(forms.ModelForm):
#     username = forms.CharField(label='Логин')
#     password = forms.CharField(label='Пароль',widget=forms.PasswordInput())
#     password2 = forms.CharField(label='Повтор пароля',widget=forms.PasswordInput())
#
#     class Meta:
#         model = get_user_model()
#         fields = ['username', 'email', 'first_name', 'last_name', 'password', 'password2']
#         labels = {
#             'email': 'E-mail',
#             'first_name': 'Имя',
#             'last_name': 'Фамилия',
#         }
#
#     def clean_password2(self):
#         cd = self.cleaned_data
#         if cd['password'] != cd['password2']:
#             raise forms.ValidationError('Пароли не совпадают')
#         return cd['password']
#
#     def clean_email(self):
#         email = self.cleaned_data['email']
#         if get_user_model().objects.filter(email=email).exists():
#             raise forms.ValidationError('Такой E-mail уже есть в базе данных')
#         return email

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль',widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля',widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )
    
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


        # fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        # labels = {
        #     'email': 'E-mail',
        #     'first_name': 'Имя',
        #     'last_name': 'Фамилия',
        # }
        # widgets = {
        #     'email': forms.TextInput(attrs={'class': 'form-input'}),
        #     'first_name': forms.TextInput(attrs={'class': 'form-input'}),
        #     'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        # }

    # def clean_password2(self): # происходит в UserCreationForm
    #     cd = self.cleaned_data
    #     if cd['password1'] != cd['password2']:
    #         raise forms.ValidationError('Пароли не совпадают')
    #     return cd['password1']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Такой E-mail уже есть в базе данных')
        return email




class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))
    this_year = datetime.date.today().year
    date_birth = forms.DateTimeField(widget=forms.SelectDateWidget(years=tuple(range(this_year-100, this_year-2))))

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'first_name', 'last_name', 'date_birth']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }




class UserPasswordChangeForm(PasswordChangeForm):

    old_password = forms.CharField(label='Старый пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label='Новый пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

sitetest/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}



{% block content %}

    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-lg-5 col-md-7 p-4 mb-4 mx-3 rounded custom-shadow">
                    <h2 class="text-center mb-4">Авторизация</h2>
                    <form  action="{% url "users:login" %}" method="post">
                        {% csrf_token %}
                        {% if request.GET.next %}
                            <input type="hidden" name="next" value={{request.GET.next}}>
                        {% endif %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Имя пользователя или E-mail</label>
                            <input type="text" class="form-control"
                            value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                            name="username" id="id_username"
                            placeholder="Введите ваше имя пользователя или E-mail"
                            required>
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">Пароль</label>
                            <input type="password" class="form-control" name="password" id="id_password"
                            placeholder="Введите ваш пароль" required>
                        </div>


                        <button type="submit" class="btn btn-dark btn-block">Войти</button>
                    </form>
                    <div class="mt-3">
                        <a href="{% url 'users:password_reset' %}">Забыли пароль?</a> | <a href="{% url "users:register" %}">Создать аккаунт</a>
                    </div>
                    <hr>
                    <div class="text-center">
                        <p>Или авторизуйтесь через:</p>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "icons/google.svg" %}" alt="Catalog Icon" width="16" height="16">
                            Google
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
                            Facebook
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
                            GitHub
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

sitetest/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль успешно изменен</h1>

<p>Вы успешно сменили пароль. <a href="{% url 'users:profile' %}">Вернуться на страницу профиля</a></p>
{% endblock %}

sitetest/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load cache %}

{% block content %}
    {% load carts_tags %}

    <div class="row">
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-1">
                </div>
                <!-- Профиль с данными пользователя -->
                <div class="col-lg-5 col-md-12">
                    <div class="profile-user p-4 mb-4 mx-1 rounded custom-shadow">
                        <h3 class="text-center mb-4">Профиль пользователя</h3>

                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}

                            {% if user.photo %}
                                <img src="{{ user.photo.url }}"
                                    alt="Аватар пользователя" class="img-fluid rounded-circle"
                                    style="max-width: 150px;">
                            {% else %}
                                <img src="{{ default_image }}"
                                    alt="Аватар пользователя" class="img-fluid rounded-circle"
                                    style="max-width: 150px;">
                            {% endif %}


                            <input type="hidden" name="next" value="{{ next }}"/>
                            <div class="form-error">{{ form.non_field_errors }}</div>

                            {% for f in form %}
                            <p class="form-text">
                                <label class="form-label" for="{{ f.id_for_label }}" >{{ f.label }}</label>
                                {{ f }}
                            </p>

                            <div class="form-error">{{ f.errors }}</div>

                            {% endfor %}

                            <div class="col-auto">
                                <button type="submit" class="btn btn-primary mt-3 mb-3 mx-3">Сохранить</button>
                            </div>
                        </form>
                        <hr>
                        <p><a href="{% url 'users:password-change' %}">Сменить пароль</a></p>
                        <p><a href="{% url "users:password_reset" %}">Сбросить пароль по E-mail</a></p>

                    </div>
                </div>


                <!-- Корзина -->
                {% user_carts request as carts %}

                <div class="col-lg-6 col-md-12">
                    <div class="p-4 mb-4 mx-2 rounded custom-shadow">
                        <div class="modal-body">
                            <h3 class="text-center mb-4">Корзина</h3>
                        <div class="cart-container" id="cart-items-container">
                                <!-- Разметка корзины -->
                                {% include "carts/includes/included_cart.html" %}
                                <!-- Закончилась разметка корзины -->
                            </div>
                        </div>
                    </div>
                </div>
                
                <!-- Оформленные заказы -->
                {% comment %} {% cache 60 user_orders user.id %} {% endcomment %}
                    <div class="col-lg-12 col-md-12">
                        <div class="p-4 mb-4 mx-2 rounded custom-shadow">
                            <h3 class="text-center mb-4">Мои заказы</h3>
                            <!-- Разметка заказов -->
                            <div class="container">
                                <div class="accordion" id="accordionExample">
                                    {% for order in orders %}
                                    <div class="accordion-item">
                                        <h2 class="accordion-header" id="heading{{ order.id }}">
                                            <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                                Заказ № {{ order.id }} - {{ order.created_timestamp }} | Статус: <strong class="mx-2">{{order.status}}</strong>
                                            </button>
                                        </h2>
                                        <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                            <div class="accordion-body">
                                                <table class="table table-dark table-hover">
                                                    <thead>
                                                        <tr>
                                                            <th>Товар</th>
                                                            <th>Количество</th>
                                                            <th>Цена</th>
                                                            <th>Общая стоимость</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        {% for item in order.orderitem_set.all %}
                                                        <tr>
                                                            <td><a class="text-white" href="{% url 'tovar' item.product.slug %}">{{ item.product.title }}</a></td>
                                                            <td>{{ item.quantity }}</td>
                                                            <td>{{ item.price }}</td>
                                                            <td>{{ item.products_price }}</td>
                                                            
                                                        </tr>
                                                        {% endfor %}
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <!-- Закончилась разметка заказов -->
                        </div>
                    </div>
                {% comment %} {% endcache %} {% endcomment %}

            </div>


        </div>  
    </div>

{% endblock %}

{% block footer %}
  <footer class="mt-4">
    <div class="container-fluid">
      <div class="row">

        <div class="col-lg-4 col-md-12 footer-txt text-center">
          <P>All Rights Reserved 2025</P>
        </div>


        <div class="col-lg-4 col-md-12 footer-txt text-center">

          <div class="row px-0">
            <nav class="nav flex-column">

              <a class="nav-link" href="{% url 'about' %}">О нас</a>

              {% if perms.pract.add_goods %}
                <a class="nav-link" href="{% url 'AddGoodsView' %}">Добавить продукцию</a>
              {% endif %}

              <a class="nav-link disabled" aria-disabled="true">Contacts</a>
              <a class="nav-link disabled" aria-disabled="true">Job</a>
            </nav>
          </div>


        </div>


        <div class="col-lg-4 col-md-12 medialinks">
          <img style="width: 40px; margin-inline: 1em;"
            src="{% static 'pract/files/instagram-vector-social-media-icon-7-june-2021-bangkok-thailand/instagram.svg' %}"
            alt="insta">
          <img style="width: 40px; margin-inline: 1em;"
            src="{% static 'pract/files/instagram-vector-social-media-icon-7-june-2021-bangkok-thailand/telegram-svgrepo-com.svg' %}"
            alt="telega">
        </div>
      </div>

    </div>
  </footer>

{% endblock footer %}

sitetest/users/templates/users/register.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Регистрация</h2>
                <form action="{% url "users:register" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Имя*</label>
                            <input type="text" class="form-control" id="id_first_name"
                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                name="first_name"
                                placeholder="Введите ваше имя" required>
                                {% if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Фамилия*</label>
                            <input type="text" class="form-control" id="id_last_name"
                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                name="last_name"
                                placeholder="Введите вашу фамилию" required>
                                {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Имя пользователя*</label>
                            <input type="text" class="form-control" id="id_username"
                                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                name="username"
                                placeholder="Введите ваше имя пользователя" required>
                                {% if form.username.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email"
                                value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                name="email"
                                placeholder="Введите ваш email" required>
                                {% if form.email.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Пароль*</label>
                            <input type="password" class="form-control" id="id_password1"
                                value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                name="password1"
                                placeholder="Введите пароль" required>
                                {% if form.password1.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                            <input type="password" class="form-control" id="id_password2"
                                value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                name="password2"
                                placeholder="Подтвердите пароль" required>
                                {% if form.password2.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                                {% endif %}
                        </div>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock  %}