sitetest/carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.CartAddView.as_view(), name='cart_add'),
    # path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.CartChangeView.as_view(), name='cart_change'),
    path('cart_remove/', views.CartRemoveView.as_view(), name='cart_remove'),
]

sitetest/sitetest/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from pract.views import page_not_found

from sitetest import settings

from django.conf.urls import handler404


urlpatterns = [
    path('', include('pract.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('carts/', include('carts.urls', namespace='carts')),   
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found
admin.site.site_header = "Карамелька админ"
admin.site.index_title = "Продукция"

sitetest/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
     path('login/', views.LoginUserView.as_view(), name='login'),     #uers:login
     path('logout/', LogoutView.as_view(), name='logout'),   #uers:logout
     path('register/', views.RegisterUserView.as_view(), name='register'),
     path('profile/', views.ProfileUser.as_view(), name='profile'),
     path('password-change/', views.UserPasswordChange.as_view(), name='password-change'),
     # path('users-cart/', views.UserCartView.as_view(), name='users_cart'),  



     path('password-change/done/',
          PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
          name='password_change_done'),

     path('password-reset/',
          PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                        email_template_name='users/password_reset_email.html',
                                        success_url=reverse_lazy("users:password_reset_done")),
          name='password_reset'),

     path('password-reset/done/',
          PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
          name='password_reset_done'),

     path('password-reset/<uidb64>/<token>',
          PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                             success_url=reverse_lazy("users:password_reset_complete")),
          name='password_reset_confirm'),

     path('password-reset/complete/',
          PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
          name='password_reset_complete'),

]

sitetest/templates/base.html
{% load static %}


<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static "css/bootstrap/bootstrap.css" %}">
  <link type="text/css" href="{% static 'css/mycss.css' %}" rel="stylesheet" />
  {% block css %}

  {% endblock %}

  <!-- Favicons for different platforms -->
  <link rel="apple-touch-icon" sizes="180x180" href="{% static "favicon/apple-touch-icon.png" %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static "favicon/favicon-32x32.png" %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static "favicon/favicon-16x16.png" %}">
  <link rel="manifest" href="{% static "favicon/site.webmanifest" %}">
  <title>{{ title }}</title>
</head>



  <header>

    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
      <div class="container">
          <a class="navbar-brand btn btn-dark btn-secondary d-flex" href="{% url 'home' %}"><img src="{% static 'pract/files/logo1.png' %}" alt="logo"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  {% comment %} <li class="nav-item">
                      <a class="nav-link  text-white" href="{% url "users:users_cart" %}">Корзина</a>
                  </li> {% endcomment %}
                  <li class="nav-item">
                    {% include "includes/cart_button.html" %}
                  </li>
                  <li class="nav-item dropdown btn btn-dark btn-secondary d-flex">
                      <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                          data-bs-toggle="dropdown" aria-expanded="false">
                          Информация
                      </a>
                      <ul class="dropdown-menu">
                          <li class="nav-item">
                              <a class="dropdown-item" href="{% url 'prices' 'all' 'all' %}">Каталог</a>
                          </li>
                          <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                          <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                      </ul>
                  </li>

                  {% if not user.is_authenticated %}
                      <li class="nav-item btn btn-dark btn-secondary d-flex">
                          <a class="nav-link  text-white" href="{% url "users:login" %}">Войти</a>
                      </li>
                  {% else %}
                      <li class="nav-item dropdown btn btn-dark btn-secondary d-flex">
                          <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                              data-bs-toggle="dropdown" aria-expanded="false">
                              Мой профиль
                          </a>
                          <ul class="dropdown-menu">
                              <li><a class="dropdown-item  text-white" href="{% url "users:profile" %}">Профиль</a>
                              </li>
                              {% if user.is_admin or user.is_staff %}
                                  <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Админ панель</a></li>
                              {% endif %}
                              <li>
                                  <hr class="dropdown-divider">
                              </li>
                              <li class="nav-item">
                                  <form id="logoutForm" method="post" action="{% url 'users:logout' %}">
                                  {% csrf_token %}
                                      <a class="dropdown-item text-white" href="{% url 'users:logout' %}" onclick="document.getElementById('logoutForm').submit(); return false;">Выйти</a>
                                  </form>
                              </li>
                          </ul>
                      </li>
                  {% endif %}
              </ul>

              <form class="d-flex" role="search" action="{% url "search" %}" method="get">
                  <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
              </form> 
              
          </div>
      </div>
    </nav>
  </header>



<body>

  <main>
    {% include "includes/notifications.html" %}
    {% block content %}
    {% endblock %}
  </main>


    {% block footer %}
    {% endblock footer %}

    <script src="{% static "js/jquery/jquery-3.7.1.min.js" %}"></script>
    <script src="{% static "js/jquery-ajax.js" %}"></script>
    <script src="{% static "js/bootstrap/bootstrap.bundle.js" %}"></script>
</body>